@extends('tutor.layout')

@section('title', 'Pembayaran Siswa')

@section('content')
<div class="space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
        <div><a href="{{ route('tutor.package-payments.index') }}" class="text-sm font-semibold text-primary hover:underline">← Kembali ke pembayaran siswa</a><p class="mt-4 text-xs font-semibold uppercase tracking-wide text-primary">{{ $session->start_at->locale('id')->translatedFormat('d F Y') }}</p><h1 class="mt-1 text-2xl font-bold text-gray-900">{{ $session->schedule?->title ?? 'Sesi belajar' }}</h1><p class="mt-1 text-sm text-gray-500">{{ $session->studyGroup->name }} · {{ $package->name }} · Rp {{ number_format($package->price, 0, ',', '.') }} / {{ ['per_session' => 'pertemuan', 'daily' => 'hari', 'monthly' => 'bulan'][$package->tutor_payment_frequency] }}</p></div>
    </div>

    <section class="overflow-hidden rounded-xl border border-gray-200 bg-white">
        <div class="border-b border-gray-100 px-5 py-4"><h2 class="font-bold text-gray-900">Status periode ini</h2><p class="mt-1 text-sm text-gray-500">Catat nominal yang benar-benar diterima dari siswa. Pembayaran Rp30.000 untuk tagihan Rp50.000 akan otomatis berstatus belum lunas dengan sisa Rp20.000.</p></div>
        <div class="overflow-x-auto"><table class="min-w-[950px] w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Siswa</th><th class="px-5 py-3">Tagihan</th><th class="px-5 py-3">Sudah diterima</th><th class="px-5 py-3">Sisa</th><th class="px-5 py-3">Status</th><th class="px-5 py-3">Catat penerimaan</th></tr></thead><tbody class="divide-y divide-gray-100">
            @forelse($currentInvoices as $invoice)
                <tr class="align-top"><td class="px-5 py-4"><p class="font-semibold text-gray-900">{{ $invoice->user->name }}</p><p class="mt-1 text-xs text-gray-500">{{ $invoice->user->email }}</p></td><td class="px-5 py-4">Rp {{ number_format($invoice->amount, 0, ',', '.') }}</td><td class="px-5 py-4">Rp {{ number_format($invoice->paid_amount, 0, ',', '.') }}</td><td class="px-5 py-4 font-semibold {{ $invoice->remaining_amount ? 'text-amber-700' : 'text-emerald-700' }}">Rp {{ number_format($invoice->remaining_amount, 0, ',', '.') }}</td><td class="px-5 py-4"><span class="rounded-full px-2.5 py-1 text-xs font-bold {{ $invoice->status === 'paid' ? 'bg-emerald-100 text-emerald-700' : ($invoice->status === 'partial' ? 'bg-amber-100 text-amber-700' : 'bg-gray-100 text-gray-600') }}">{{ $invoice->status === 'paid' ? 'Lunas' : ($invoice->status === 'partial' ? 'Belum lunas' : 'Belum bayar') }}</span></td><td class="px-5 py-4">@if($invoice->remaining_amount > 0)<form method="POST" action="{{ route('tutor.package-payments.record', $invoice) }}" class="flex flex-wrap items-center gap-2">@csrf<input type="hidden" name="class_session_id" value="{{ $session->id }}"><input required min="1" max="{{ $invoice->remaining_amount }}" name="amount" type="number" class="w-28 rounded-lg border border-gray-300 px-3 py-2" placeholder="Nominal"><select name="payment_method" class="rounded-lg border border-gray-300 px-2 py-2"><option value="cash">Tunai</option><option value="transfer">Transfer</option><option value="other">Lainnya</option></select><x-ui.button type="submit" size="sm">Simpan</x-ui.button></form>@else<p class="text-xs text-emerald-700">Lunas</p>@endif</td></tr>
            @empty<tr><td colspan="6" class="px-5 py-12 text-center text-gray-500">Belum ada tagihan untuk periode ini.</td></tr>@endforelse
        </tbody></table></div>
        @if($currentInvoices->hasPages())<div class="border-t border-gray-100 px-5 py-4">{{ $currentInvoices->links() }}</div>@endif
    </section>

    <section class="overflow-hidden rounded-xl border border-gray-200 bg-white"><div class="border-b border-gray-100 px-5 py-4"><h2 class="font-bold text-gray-900">Riwayat dan tunggakan rombel</h2><p class="mt-1 text-sm text-gray-500">Termasuk tagihan periode sebelumnya yang belum lunas.</p></div><div class="overflow-x-auto"><table class="min-w-[780px] w-full text-left text-sm"><thead class="bg-gray-50 text-xs uppercase text-gray-500"><tr><th class="px-5 py-3">Periode</th><th class="px-5 py-3">Siswa</th><th class="px-5 py-3">Diterima / sisa</th><th class="px-5 py-3">Riwayat penerimaan</th></tr></thead><tbody class="divide-y divide-gray-100">@forelse($historyInvoices as $invoice)<tr class="align-top"><td class="px-5 py-4">{{ $invoice->period_start?->locale('id')->translatedFormat('d M Y') }}@if($invoice->period_end && !$invoice->period_start?->isSameDay($invoice->period_end)) – {{ $invoice->period_end->locale('id')->translatedFormat('d M Y') }}@endif</td><td class="px-5 py-4 font-semibold text-gray-900">{{ $invoice->user->name }}</td><td class="px-5 py-4">Rp {{ number_format($invoice->paid_amount, 0, ',', '.') }} / <span class="font-semibold">Rp {{ number_format($invoice->remaining_amount, 0, ',', '.') }}</span></td><td class="px-5 py-4"><ul class="space-y-1 text-xs text-gray-600">@forelse($invoice->payments as $payment)<li>Rp {{ number_format($payment->amount, 0, ',', '.') }} · {{ $payment->paid_at->locale('id')->translatedFormat('d M Y H:i') }} · {{ $payment->paidBy?->name ?? '—' }}</li>@empty<li>Belum ada penerimaan.</li>@endforelse</ul></td></tr>@empty<tr><td colspan="4" class="px-5 py-12 text-center text-gray-500">Belum ada riwayat pembayaran.</td></tr>@endforelse</tbody></table></div>@if($historyInvoices->hasPages())<div class="border-t border-gray-100 px-5 py-4">{{ $historyInvoices->links() }}</div>@endif</section>
</div>
@endsection
