@extends('tutor.layout')

@section('title', 'Laporan Perkembangan Sesi')

@section('content')
@php($isEditing = isset($report))
<div class="mx-auto max-w-4xl space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('tutor.schedule.index', ['range' => 'today']) }}" class="text-sm font-semibold text-primary hover:underline">← Kembali ke Jadwal Hari Ini</a><p class="mt-4 text-xs font-semibold uppercase tracking-wide text-primary">Laporan dari sesi terjadwal</p><h1 class="mt-1 text-2xl font-bold text-gray-900">{{ $session->schedule?->title ?? $session->class?->title ?? 'Sesi belajar' }}</h1><p class="mt-1 text-sm text-gray-500">{{ $session->start_at->locale('id')->translatedFormat('l, d F Y · H:i') }} WIB · {{ $session->studyGroup?->name ?? 'Sesi personal' }}</p></div></div>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $isEditing ? route('tutor.schedule.progress.update', [$session, $report]) : route('tutor.schedule.progress.store', $session) }}" class="space-y-5 rounded-2xl border border-gray-200 bg-white p-5 sm:p-6">@csrf @if($isEditing) @method('PUT') @endif
        <div class="flex items-center justify-between border-b border-gray-100 pb-4"><div><h2 class="font-bold text-gray-900">{{ $isEditing ? 'Edit laporan perkembangan' : 'Buat laporan perkembangan' }}</h2><p class="mt-1 text-sm text-gray-500">Laporan hanya dapat dibuat untuk peserta sesi ini.</p></div></div>
        @if($isEditing)<input type="hidden" name="user_id" value="{{ $report->user_id }}"><div class="rounded-xl bg-gray-50 px-4 py-3 text-sm"><span class="text-gray-500">Siswa</span><p class="mt-1 font-bold text-gray-900">{{ $report->user->name }}</p></div>@else<label class="block"><span class="text-sm font-semibold text-gray-700">Siswa</span><select name="user_id" required class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2.5"><option value="">Pilih peserta sesi</option>@foreach($students as $student)<option value="{{ $student->id }}" @selected(old('user_id') == $student->id)>{{ $student->name }} · {{ $student->email }}</option>@endforeach</select></label>@endif
        <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">@foreach(['progress_percent' => 'Progres', 'mastery_score' => 'Penguasaan', 'discipline_score' => 'Disiplin', 'participation_score' => 'Partisipasi'] as $field => $label)<label><span class="text-sm font-semibold text-gray-700">{{ $label }} (0–100)</span><input type="number" name="{{ $field }}" min="0" max="100" value="{{ old($field, $report->$field ?? '') }}" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2.5"></label>@endforeach</div>
        @foreach(['summary' => 'Ringkasan perkembangan', 'strengths' => 'Kekuatan', 'improvements' => 'Yang perlu ditingkatkan', 'next_target' => 'Target berikutnya'] as $field => $label)<label class="block"><span class="text-sm font-semibold text-gray-700">{{ $label }}</span><textarea name="{{ $field }}" rows="{{ $field === 'summary' ? 4 : 3 }}" {{ $field === 'summary' ? 'required' : '' }} class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2.5">{{ old($field, $report->$field ?? '') }}</textarea></label>@endforeach
        <button class="inline-flex items-center gap-2 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-white hover:bg-primary/90"><i class="ri-save-line"></i>{{ $isEditing ? 'Simpan perubahan' : 'Simpan laporan' }}</button>
    </form>
    @if(! $isEditing)<section class="rounded-2xl border border-gray-200 bg-white p-5 sm:p-6"><h2 class="font-bold text-gray-900">Laporan pada sesi ini</h2><div class="mt-4 divide-y divide-gray-100">@forelse($reports as $item)<article class="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-start sm:justify-between"><div><p class="font-bold text-gray-900">{{ $item->user->name }}</p><p class="mt-1 text-sm text-gray-600">{{ $item->summary }}</p></div><div class="flex gap-3 text-sm font-semibold"><a href="{{ route('tutor.schedule.progress.edit', [$session, $item]) }}" class="text-primary hover:underline">Edit</a><form method="POST" action="{{ route('tutor.schedule.progress.destroy', [$session, $item]) }}" onsubmit="return confirm('Hapus laporan ini?');">@csrf @method('DELETE')<button class="text-red-600 hover:underline">Hapus</button></form></div></article>@empty<p class="py-8 text-center text-sm text-gray-500">Belum ada laporan untuk sesi ini.</p>@endforelse</div></section>@endif
</div>
@endsection
