@extends('tutor.layout')

@section('title', 'Catatan Progress Sesi')

@section('content')
@php($isEditing = isset($report))
<div class="mx-auto max-w-4xl space-y-6">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between"><div><a href="{{ route('tutor.schedule.index', ['range' => 'today']) }}" class="text-sm font-semibold text-primary hover:underline">← Kembali ke Penjadwalan</a><p class="mt-4 text-xs font-semibold uppercase tracking-wide text-primary">Catatan internal per sesi</p><h1 class="mt-1 text-2xl font-bold text-gray-900">{{ $session->schedule?->title ?? $session->class?->title ?? 'Sesi belajar' }}</h1><p class="mt-1 text-sm text-gray-500">{{ $session->start_at->locale('id')->translatedFormat('l, d F Y · H:i') }} WIB · {{ $session->studyGroup?->name ?? 'Sesi personal' }}</p></div></div>
    @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
    <form method="POST" action="{{ $isEditing ? route('tutor.schedule.progress.update', [$session, $report]) : route('tutor.schedule.progress.store', $session) }}" class="space-y-5 rounded-2xl border border-gray-200 bg-white p-5 sm:p-6">@csrf @if($isEditing) @method('PUT') @endif
        <div class="flex items-center justify-between border-b border-gray-100 pb-4"><div><h2 class="font-bold text-gray-900">{{ $isEditing ? 'Edit catatan progress' : 'Buat catatan progress' }}</h2><p class="mt-1 text-sm text-gray-500">Catatan ini hanya untuk tutor sebagai pengingat tindak lanjut, bukan untuk peserta atau orang tua.</p></div></div>
        @if($isEditing)<input type="hidden" name="user_id" value="{{ $report->user_id }}"><div class="rounded-xl bg-gray-50 px-4 py-3 text-sm"><span class="text-gray-500">Peserta yang dicatat</span><p class="mt-1 font-bold text-gray-900">{{ $report->user->name }}</p></div>@else<x-ui.input.select name="user_id" label="Peserta yang dicatat" placeholder="Pilih peserta sesi" :required="true"><option value="" disabled>Pilih peserta sesi</option>@foreach($students as $student)<option value="{{ $student->id }}" @selected(old('user_id') == $student->id)>{{ $student->name }} · {{ $student->email }}</option>@endforeach</x-ui.input.select>@endif
        <x-ui.input.textarea name="summary" label="Catatan progress" :value="old('summary', $report->summary ?? '')" :required="true" rows="8" resize="vertical" helper="Simpan poin pembelajaran, hal yang perlu diingat, dan tindak lanjut untuk sesi berikutnya." data-summernote data-height="280" data-toolbar='[["style",["style"]],["font",["bold","italic","underline","clear"]],["para",["ul","ol","paragraph"]],["insert",["link"]],["view",["codeview"]]]' class="summernote-field" />
        <x-ui.button type="submit" icon="ri-save-line">{{ $isEditing ? 'Simpan perubahan' : 'Simpan catatan' }}</x-ui.button>
    </form>
    @if(! $isEditing)<section class="rounded-2xl border border-gray-200 bg-white p-5 sm:p-6"><h2 class="font-bold text-gray-900">Catatan progress pada sesi ini</h2><div class="mt-4 divide-y divide-gray-100">@forelse($reports as $item)<article class="flex flex-col gap-3 py-4 first:pt-0 sm:flex-row sm:items-start sm:justify-between"><div><p class="font-bold text-gray-900">{{ $item->user->name }}</p><div class="prose prose-sm mt-1 max-w-none text-gray-600">{!! \App\Support\RichTextSanitizer::sanitize($item->summary) !!}</div></div><div class="flex gap-3 text-sm font-semibold"><a href="{{ route('tutor.schedule.progress.edit', [$session, $item]) }}" class="text-primary hover:underline">Edit</a><form method="POST" action="{{ route('tutor.schedule.progress.destroy', [$session, $item]) }}" onsubmit="return confirm('Hapus catatan progress ini?');">@csrf @method('DELETE')<button class="text-red-600 hover:underline">Hapus</button></form></div></article>@empty<p class="py-8 text-center text-sm text-gray-500">Belum ada catatan progress untuk sesi ini.</p>@endforelse</div></section>@endif
</div>
@endsection

@include('admin.partials.summernote')
