@extends('tutor.layout')
@section('title', 'Pengajuan Cuti')
@section('content')
<div class="space-y-6">
 <div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><h1 class="text-2xl font-bold text-gray-900">Pengajuan Cuti</h1><p class="mt-1 text-sm text-gray-500">Atur waktu tidak tersedia untuk ditinjau admin.</p></div><button type="button" onclick="openLeaveModal()" class="inline-flex w-fit items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white"><i class="ri-add-line"></i>Ajukan Cuti</button></div>
 @if(session('success'))<div class="rounded-xl border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-800">{{ session('success') }}</div>@endif
 @if($errors->any())<div class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ $errors->first() }}</div>@endif
 <section class="overflow-hidden rounded-2xl border border-gray-200 bg-white"><div class="border-b border-gray-100 px-5 py-4"><h2 class="font-bold text-gray-900">Riwayat Pengajuan</h2></div><div class="divide-y divide-gray-100">@forelse($leaves as $leave)@php($statusClass=['approved'=>'bg-green-50 text-green-700 border-green-200','rejected'=>'bg-red-50 text-red-700 border-red-200'][$leave->status]??'bg-amber-50 text-amber-700 border-amber-200')<article class="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><p class="font-semibold text-gray-900">{{ $leave->start_at->translatedFormat('d M Y H:i') }} – {{ $leave->end_at->translatedFormat('d M Y H:i') }}</p><p class="mt-1 text-sm text-gray-500">{{ $leave->reason }}</p>@if($leave->admin_notes)<p class="mt-1 text-xs text-red-600">Catatan admin: {{ $leave->admin_notes }}</p>@endif</div><span class="w-fit rounded-full border px-3 py-1 text-xs font-bold {{ $statusClass }}">{{ ['pending'=>'Menunggu review','approved'=>'Disetujui','rejected'=>'Ditolak'][$leave->status]??$leave->status }}</span></article>@empty<div class="p-12 text-center text-sm text-gray-500"><i class="ri-calendar-close-line mb-2 block text-3xl text-gray-300"></i>Belum ada pengajuan cuti.</div>@endforelse</div></section>{{ $leaves->links() }}
</div>
<div id="leaveModal" class="fixed inset-0 z-50 hidden items-center justify-center bg-gray-900/50 p-4"><div class="w-full max-w-lg rounded-2xl bg-white shadow-2xl"><div class="flex items-center justify-between border-b border-gray-100 px-5 py-4"><div><p class="text-xs font-semibold uppercase tracking-wide text-gray-400">Ketersediaan tutor</p><h2 class="font-bold text-gray-900">Ajukan Cuti</h2></div><button type="button" onclick="closeLeaveModal()" class="rounded-lg p-2 text-gray-400 hover:bg-gray-100"><i class="ri-close-line text-xl"></i></button></div><form method="POST" action="{{ route('tutor.leave.store') }}" class="space-y-5 p-5">@csrf<div class="grid gap-4 sm:grid-cols-2"><label class="block"><span class="text-sm font-semibold text-gray-700">Mulai cuti</span><input type="datetime-local" name="start_at" required class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label><label class="block"><span class="text-sm font-semibold text-gray-700">Selesai cuti</span><input type="datetime-local" name="end_at" required class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></label></div><label class="block"><span class="text-sm font-semibold text-gray-700">Alasan</span><textarea name="reason" required maxlength="1000" rows="4" placeholder="Contoh: keperluan keluarga" class="mt-2 w-full rounded-lg border border-gray-300 px-3 py-2.5 text-sm"></textarea></label><div class="flex justify-end gap-3"><button type="button" onclick="closeLeaveModal()" class="rounded-lg border border-gray-300 px-4 py-2 text-sm font-semibold text-gray-700">Batal</button><button class="rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white">Kirim Pengajuan</button></div></form></div></div>
@endsection
@section('scripts')<script>function openLeaveModal(){document.getElementById('leaveModal').classList.replace('hidden','flex')}function closeLeaveModal(){const modal=document.getElementById('leaveModal');modal.classList.add('hidden');modal.classList.remove('flex')}</script>@endsection
