@extends('parent.layout')

@section('title', 'Riwayat Ujian')

@section('content')
<div class="space-y-5">
    <header><p class="text-sm font-semibold text-primary">Evaluasi belajar</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900">Riwayat ujian</h1><p class="mt-1 text-sm text-gray-500">Hasil tryout dan ujian yang telah diselesaikan {{ $child?->name ?? 'anak' }}.</p></header>
    @if($child)
        <section class="grid gap-3 sm:grid-cols-3"><article class="rounded-xl border border-slate-200 bg-white p-4"><div class="flex items-center justify-between"><p class="text-sm font-medium text-gray-500">Ujian selesai</p><i class="ri-file-list-3-line text-lg text-primary"></i></div><p class="mt-4 text-3xl font-bold text-gray-900">{{ $assessmentSummary['completed'] }}</p><p class="mt-2 text-xs text-gray-500">riwayat yang tercatat</p></article><article class="rounded-xl border border-slate-200 bg-white p-4"><div class="flex items-center justify-between"><p class="text-sm font-medium text-gray-500">Rata-rata nilai</p><i class="ri-line-chart-line text-lg text-emerald-600"></i></div><p class="mt-4 text-3xl font-bold text-gray-900">{{ $assessmentSummary['completed'] ? number_format($assessmentSummary['average_score'], 1) : '—' }}</p><p class="mt-2 text-xs text-gray-500">dari seluruh ujian selesai</p></article><article class="rounded-xl border border-slate-200 bg-white p-4"><div class="flex items-center justify-between"><p class="text-sm font-medium text-gray-500">Nilai tertinggi</p><i class="ri-medal-line text-lg text-amber-500"></i></div><p class="mt-4 text-3xl font-bold text-gray-900">{{ $assessmentSummary['completed'] ? number_format($assessmentSummary['highest_score'], 1) : '—' }}</p><p class="mt-2 text-xs text-gray-500">pencapaian terbaik anak</p></article></section>
        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="flex flex-col gap-1 border-b border-slate-100 px-5 py-4 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-gray-900">Daftar hasil ujian</h2><p class="mt-1 text-sm text-gray-500">Urut dari ujian yang paling baru selesai.</p></div><span class="w-fit rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-gray-600">{{ $answers instanceof \Illuminate\Pagination\AbstractPaginator ? $answers->total() : $answers->count() }} hasil</span></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left text-sm"><thead class="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3">Ujian</th><th class="px-5 py-3">Subtes</th><th class="px-5 py-3">Nilai</th><th class="px-5 py-3">Jawaban benar</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($answers as $answer)<tr><td class="px-5 py-4 text-gray-600">{{ $answer->finished_at?->translatedFormat('d M Y · H:i') ?? '—' }}</td><td class="max-w-xs px-5 py-4 font-semibold text-gray-900">{{ $answer->tryout?->name ?? 'Tryout' }}</td><td class="px-5 py-4 text-gray-600">{{ $answer->tryoutDetail?->display_name ?? '—' }}</td><td class="px-5 py-4"><span class="rounded-lg bg-primary/10 px-3 py-1.5 font-bold text-primary">{{ $answer->score !== null ? number_format((float) $answer->score, 1) : '—' }}</span></td><td class="px-5 py-4 text-gray-600">{{ $answer->correct_answers ?? '—' }}/{{ $answer->total_questions ?? '—' }}</td></tr>@empty<tr><td colspan="5" class="px-5 py-14 text-center text-gray-500"><i class="ri-file-search-line mb-2 block text-3xl text-slate-300"></i>Belum ada ujian yang selesai.</td></tr>@endforelse</tbody></table></div>@if($answers instanceof \Illuminate\Pagination\AbstractPaginator)<div class="border-t border-slate-100 px-5 py-4">{{ $answers->links() }}</div>@endif</section>
    @endif
</div>
@endsection
