@extends('parent.layout')

@section('title', 'Perkembangan Belajar')

@section('content')
<div class="space-y-5" x-data="{ tab: 'progress' }">
    <header><p class="text-sm font-semibold text-primary">Pemantauan tutor</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900">Perkembangan belajar</h1><p class="mt-1 text-sm text-gray-500">Laporan progres dan feedback yang dapat dilihat oleh orang tua.</p></header>
    @if($child)
        <div class="inline-flex rounded-xl border border-slate-200 bg-white p-1.5"><button @click="tab = 'progress'" :class="tab === 'progress' ? 'bg-primary text-white' : 'text-gray-600 hover:bg-slate-50'" class="rounded-lg px-4 py-2 text-sm font-semibold transition-colors">Laporan progres</button><button @click="tab = 'feedback'" :class="tab === 'feedback' ? 'bg-primary text-white' : 'text-gray-600 hover:bg-slate-50'" class="rounded-lg px-4 py-2 text-sm font-semibold transition-colors">Feedback tutor</button></div>

        <section x-show="tab === 'progress'" class="space-y-4">@forelse($progress as $report)<article class="rounded-xl border border-slate-200 bg-white p-5 sm:p-6"><div class="flex flex-col gap-3 border-b border-slate-100 pb-4 sm:flex-row sm:items-start sm:justify-between"><div><h2 class="font-bold text-gray-900">{{ $report->package?->name ?? 'Laporan perkembangan' }}</h2><p class="mt-1 text-sm text-gray-500">{{ $report->tentor?->name ?? 'Tutor' }} · {{ $report->studyGroup?->name ?? 'Personal' }}</p><p class="mt-1 text-xs text-gray-400">{{ $report->period_start?->translatedFormat('d M') }}–{{ $report->period_end?->translatedFormat('d M Y') }}</p></div><span class="w-fit rounded-lg bg-primary/10 px-3 py-1.5 text-sm font-bold text-primary">Progres {{ $report->progress_percent ?? '—' }}%</span></div><div class="mt-5 grid gap-3 sm:grid-cols-3">@foreach(['mastery_score'=>'Penguasaan', 'discipline_score'=>'Disiplin', 'participation_score'=>'Partisipasi'] as $field => $label)<div class="rounded-lg border border-slate-100 bg-slate-50 p-3"><p class="text-xs font-medium text-gray-500">{{ $label }}</p><p class="mt-1 text-xl font-bold text-gray-900">{{ $report->{$field} ?? '—' }}@if($report->{$field} !== null)<span class="text-xs font-medium text-gray-400">/100</span>@endif</p></div>@endforeach</div><div class="mt-5 space-y-4 text-sm leading-6 text-gray-600"><div><p class="font-semibold text-gray-800">Ringkasan tutor</p><p class="mt-1 whitespace-pre-line">{{ $report->summary }}</p></div>@if($report->strengths)<div class="border-l-2 border-emerald-300 pl-3"><p class="font-semibold text-gray-800">Kekuatan</p><p class="mt-1 whitespace-pre-line">{{ $report->strengths }}</p></div>@endif@if($report->improvements)<div class="border-l-2 border-amber-300 pl-3"><p class="font-semibold text-gray-800">Perlu ditingkatkan</p><p class="mt-1 whitespace-pre-line">{{ $report->improvements }}</p></div>@endif@if($report->next_target)<div class="border-l-2 border-primary/50 pl-3"><p class="font-semibold text-gray-800">Target berikutnya</p><p class="mt-1 whitespace-pre-line">{{ $report->next_target }}</p></div>@endif</div></article>@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white px-5 py-14 text-center text-sm text-gray-500"><i class="ri-line-chart-line mb-2 block text-3xl text-slate-300"></i>Tutor belum membuat laporan progres.</div>@endforelse@if($progress instanceof \Illuminate\Pagination\AbstractPaginator){{ $progress->links() }}@endif</section>

        <section x-show="tab === 'feedback'" x-cloak class="space-y-4">@forelse($feedback as $item)<article class="rounded-xl border border-slate-200 bg-white p-5"><div class="flex flex-col gap-3 border-b border-slate-100 pb-4 sm:flex-row sm:items-start sm:justify-between"><div class="flex gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-lg text-primary"><i class="ri-message-3-line"></i></span><div><h2 class="font-bold text-gray-900">{{ $item->title }}</h2><p class="mt-1 text-sm text-gray-500">{{ $item->tentor?->name ?? 'Tutor' }} · {{ $item->studyGroup?->name ?? 'Personal' }}</p></div></div><span class="text-xs text-gray-400">{{ $item->created_at?->translatedFormat('d M Y') }}</span></div><p class="mt-4 whitespace-pre-line text-sm leading-7 text-gray-600">{{ $item->feedback }}</p></article>@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white px-5 py-14 text-center text-sm text-gray-500"><i class="ri-message-3-line mb-2 block text-3xl text-slate-300"></i>Belum ada feedback dari tutor.</div>@endforelse@if($feedback instanceof \Illuminate\Pagination\AbstractPaginator){{ $feedback->links() }}@endif</section>
    @endif
</div>
@endsection
