@extends('parent.layout')

@section('title', 'Paket dan Pembayaran')

@section('content')
<div class="space-y-5">
    <header><p class="text-sm font-semibold text-primary">Program belajar</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900">Paket & pembayaran</h1><p class="mt-1 text-sm text-gray-500">Status akses belajar dan transaksi {{ $child?->name ?? 'anak' }}.</p></header>
    @if($child)
        <section class="grid gap-4 md:grid-cols-2 xl:grid-cols-3">@forelse($accesses as $access)<article class="rounded-xl border border-slate-200 bg-white p-5"><div class="flex items-start justify-between gap-3"><span class="flex h-10 w-10 shrink-0 items-center justify-center rounded-lg bg-primary/10 text-lg text-primary"><i class="ri-book-open-line"></i></span><span class="rounded-full px-2.5 py-1 text-xs font-semibold {{ $access->is_active ? 'bg-emerald-50 text-emerald-700' : 'bg-slate-100 text-slate-600' }}">{{ $access->is_active ? 'Aktif' : 'Tidak aktif' }}</span></div><h2 class="mt-4 text-base font-bold text-gray-900">{{ $access->package?->name ?? 'Paket belajar' }}</h2><dl class="mt-5 divide-y divide-slate-100 text-sm"><div class="flex justify-between gap-3 py-2.5 first:pt-0"><dt class="text-gray-500">Masa aktif</dt><dd class="text-right font-medium text-gray-800">{{ $access->end_date?->translatedFormat('d M Y') ?? 'Tanpa batas' }}</dd></div><div class="flex justify-between gap-3 py-2.5"><dt class="text-gray-500">Sisa hari</dt><dd class="font-semibold text-gray-800">{{ $access->days_remaining ?? '—' }}</dd></div><div class="flex justify-between gap-3 py-2.5 pb-0"><dt class="text-gray-500">Sesi booking</dt><dd class="font-medium text-gray-800">{{ $access->completed_booking_count }} tercatat</dd></div></dl></article>@empty<div class="rounded-xl border border-dashed border-slate-300 bg-white px-5 py-14 text-center text-sm text-gray-500 md:col-span-2 xl:col-span-3"><i class="ri-book-open-line mb-2 block text-3xl text-slate-300"></i>Belum ada paket untuk anak ini.</div>@endforelse</section>
        @if($accesses instanceof \Illuminate\Pagination\AbstractPaginator){{ $accesses->links() }}@endif
        <section class="overflow-hidden rounded-xl border border-slate-200 bg-white"><div class="flex items-center justify-between border-b border-slate-100 px-5 py-4"><div><h2 class="font-bold text-gray-900">Riwayat pembayaran</h2><p class="mt-1 text-sm text-gray-500">Transaksi yang tercatat untuk {{ $child->name }}.</p></div><i class="ri-secure-payment-line text-xl text-primary"></i></div><div class="overflow-x-auto"><table class="w-full min-w-[620px] text-left text-sm"><thead class="border-b border-slate-100 bg-slate-50 text-xs uppercase tracking-wide text-gray-500"><tr><th class="px-5 py-3">Tanggal</th><th class="px-5 py-3">Paket</th><th class="px-5 py-3">Nominal</th><th class="px-5 py-3">Status</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($payments as $payment)<tr><td class="px-5 py-4 text-gray-600">{{ $payment->created_at?->translatedFormat('d M Y') ?? '—' }}</td><td class="px-5 py-4 font-semibold text-gray-900">{{ $payment->package?->name ?? '—' }}</td><td class="px-5 py-4 font-medium text-gray-800">Rp {{ number_format((int) $payment->total_amount, 0, ',', '.') }}</td><td class="px-5 py-4"><span class="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-semibold text-slate-700">{{ ucfirst($payment->status) }}</span></td></tr>@empty<tr><td colspan="4" class="px-5 py-14 text-center text-gray-500">Belum ada transaksi.</td></tr>@endforelse</tbody></table></div>@if($payments instanceof \Illuminate\Pagination\AbstractPaginator)<div class="border-t border-slate-100 px-5 py-4">{{ $payments->links() }}</div>@endif</section>
    @endif
</div>
@endsection
