@extends('parent.layout')
@section('title', 'Laporan Cetak')
@push('styles')<style>@media print { header, aside, .no-print { display:none!important } body{background:#fff}.mx-auto{max-width:none!important;padding:0!important}.grid{display:block!important}.rounded-2xl{break-inside:avoid;margin-bottom:16px} }</style>@endpush
@section('content')
<div class="space-y-6"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between no-print"><div><h1 class="text-2xl font-bold text-gray-900">Laporan Belajar</h1><p class="mt-1 text-sm text-gray-500">Cetak atau simpan sebagai PDF dari browser.</p></div><button onclick="window.print()" class="inline-flex w-fit items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white"><i class="ri-printer-line"></i>Cetak / Simpan PDF</button></div>
<section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><p class="text-sm text-gray-500">Laporan perkembangan siswa</p><h2 class="mt-1 text-2xl font-bold text-gray-900">{{ $child->name }}</h2><p class="mt-1 text-sm text-gray-500">Dicetak pada {{ now()->translatedFormat('d F Y') }}</p><div class="mt-6 grid grid-cols-2 gap-4 sm:grid-cols-4">@foreach(['total'=>'Total sesi','present'=>'Hadir','late'=>'Terlambat','absent'=>'Alpa'] as $key=>$label)<div class="rounded-xl bg-gray-50 p-4"><p class="text-xs text-gray-500">{{ $label }}</p><p class="mt-1 text-xl font-bold">{{ $attendanceSummary[$key] }}</p></div>@endforeach</div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><h2 class="font-bold text-gray-900">Paket belajar</h2><div class="mt-4 space-y-2 text-sm">@forelse($packages as $access)<p class="flex justify-between gap-4 border-b border-gray-100 pb-2"><span>{{ $access->package?->name }}</span><span>{{ $access->end_date?->translatedFormat('d M Y') ?? 'Tanpa batas' }}</span></p>@empty<p class="text-gray-500">Belum ada paket.</p>@endforelse</div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><h2 class="font-bold text-gray-900">Hasil ujian terakhir</h2><div class="mt-4 space-y-2 text-sm">@forelse($answers as $answer)<p class="flex justify-between gap-4 border-b border-gray-100 pb-2"><span>{{ $answer->tryout?->name ?? 'Tryout' }}</span><span class="font-semibold">{{ number_format((float) $answer->score, 1) }} · {{ $answer->finished_at?->translatedFormat('d M Y') }}</span></p>@empty<p class="text-gray-500">Belum ada ujian selesai.</p>@endforelse</div></section>
<section class="rounded-2xl border border-gray-200 bg-white p-6 shadow-sm"><h2 class="font-bold text-gray-900">Catatan tutor</h2><div class="mt-4 space-y-5">@forelse($progress as $item)<article><p class="font-semibold">{{ $item->package?->name ?? 'Perkembangan belajar' }} · {{ $item->tentor?->name }}</p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-gray-600">{{ $item->summary }}</p>@if($item->next_target)<p class="mt-2 text-sm"><span class="font-semibold">Target berikutnya:</span> {{ $item->next_target }}</p>@endif</article>@empty<p class="text-gray-500">Belum ada laporan tutor.</p>@endforelse</div></section></div>
@endsection
