@extends('parent.layout')

@section('title', 'Laporan Cetak')

@push('styles')
<style>@media print { header, aside, .no-print { display:none!important } body{background:#fff}.responsive-shell{max-width:none!important;padding:0!important}.grid{display:block!important}.rounded-xl{break-inside:avoid;margin-bottom:16px} }</style>
@endpush

@section('content')
<div class="space-y-5">
    <header class="no-print flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-semibold text-primary">Dokumen ringkasan</p><h1 class="mt-1 text-2xl font-bold tracking-tight text-gray-900">Laporan belajar</h1><p class="mt-1 text-sm text-gray-500">Cetak atau simpan PDF untuk dokumentasi perkembangan anak.</p></div><button onclick="window.print()" class="inline-flex w-fit items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-sm font-semibold text-white"><i class="ri-printer-line"></i>Cetak / Simpan PDF</button></header>
    <section class="rounded-xl border border-slate-200 bg-white p-6"><div class="flex items-start justify-between gap-4"><div><p class="text-sm font-medium text-gray-500">Laporan perkembangan siswa</p><h2 class="mt-1 text-2xl font-bold text-gray-900">{{ $child->name }}</h2><p class="mt-1 text-sm text-gray-500">Dicetak pada {{ now()->translatedFormat('d F Y') }}</p></div><span class="flex h-11 w-11 items-center justify-center rounded-full bg-primary/10 text-lg text-primary"><i class="ri-file-chart-line"></i></span></div><div class="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-4">@foreach(['total'=>'Total sesi', 'present'=>'Hadir', 'late'=>'Terlambat', 'absent'=>'Alpa'] as $key => $label)<div class="rounded-lg border border-slate-100 bg-slate-50 p-3"><p class="text-xs font-medium text-gray-500">{{ $label }}</p><p class="mt-1 text-xl font-bold text-gray-900">{{ $attendanceSummary[$key] }}</p></div>@endforeach</div></section>
    <section class="grid gap-5 xl:grid-cols-2"><article class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-bold text-gray-900">Paket belajar</h2><div class="mt-4 divide-y divide-slate-100 text-sm">@forelse($packages as $access)<div class="flex justify-between gap-4 py-3 first:pt-0"><span class="font-medium text-gray-800">{{ $access->package?->name ?? 'Paket belajar' }}</span><span class="shrink-0 text-gray-500">{{ $access->end_date?->translatedFormat('d M Y') ?? 'Tanpa batas' }}</span></div>@empty<p class="py-8 text-center text-gray-500">Belum ada paket.</p>@endforelse</div></article><article class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-bold text-gray-900">Hasil ujian terakhir</h2><div class="mt-4 divide-y divide-slate-100 text-sm">@forelse($answers as $answer)<div class="flex justify-between gap-4 py-3 first:pt-0"><div class="min-w-0"><p class="truncate font-medium text-gray-800">{{ $answer->tryout?->name ?? 'Tryout' }}</p><p class="mt-1 text-xs text-gray-400">{{ $answer->finished_at?->translatedFormat('d M Y') }}</p></div><span class="shrink-0 font-bold text-primary">{{ number_format((float) $answer->score, 1) }}</span></div>@empty<p class="py-8 text-center text-gray-500">Belum ada ujian selesai.</p>@endforelse</div></article></section>
    <section class="rounded-xl border border-slate-200 bg-white p-5"><h2 class="font-bold text-gray-900">Catatan tutor</h2><div class="mt-4 divide-y divide-slate-100">@forelse($progress as $item)<article class="py-4 first:pt-0"><p class="font-semibold text-gray-800">{{ $item->package?->name ?? 'Perkembangan belajar' }} <span class="font-normal text-gray-400">· {{ $item->tentor?->name }}</span></p><p class="mt-2 whitespace-pre-line text-sm leading-6 text-gray-600">{{ $item->summary }}</p>@if($item->next_target)<p class="mt-2 text-sm text-gray-600"><span class="font-semibold text-gray-800">Target berikutnya:</span> {{ $item->next_target }}</p>@endif</article>@empty<p class="py-10 text-center text-gray-500">Belum ada laporan tutor.</p>@endforelse</div></section>
</div>
@endsection
