@extends('super-admin.layouts.app')

@section('content')
<div class="w-full space-y-6">
    <div><h1 class="text-2xl font-bold text-gray-900">Load Test Tryout</h1><p class="mt-1 text-sm text-gray-500">Buat akun uji, unduh CSV untuk k6, reset percobaan, atau hapus satu batch tanpa terminal.</p></div>
    @if(session('success'))<div class="rounded-lg border border-green-200 bg-green-50 px-4 py-3 text-sm text-green-700">{{ session('success') }}</div>@endif
    <div class="rounded-xl border border-amber-200 bg-amber-50 p-5 text-sm text-amber-800"><i class="ri-error-warning-line mr-2 text-lg"></i>Gunakan tryout khusus testing. Akun test adalah akun nyata ber-domain <code>loadtest.invalid</code> dan proses k6 akan membuat hasil pengerjaan.</div>
    <form method="POST" action="{{ route('super-admin.load-test.create') }}" class="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">@csrf
        <h2 class="text-lg font-semibold text-gray-900">Buat batch akun</h2>
        <div class="mt-5 grid gap-4 md:grid-cols-3"><label class="block text-sm font-semibold text-gray-700">Tryout<select name="tryout_id" required class="mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm focus:border-primary focus:ring-primary"><option value="">Pilih tryout</option>@foreach($tryouts as $tryout)<option value="{{ $tryout->tryout_id }}">#{{ $tryout->tryout_id }} — {{ $tryout->name }}</option>@endforeach</select></label><label class="block text-sm font-semibold text-gray-700">Jumlah akun<input name="count" type="number" min="1" max="2000" value="{{ old('count', 324) }}" required class="mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm focus:border-primary focus:ring-primary"></label><label class="block text-sm font-semibold text-gray-700">Nama batch (opsional)<input name="batch" value="{{ old('batch') }}" pattern="[a-z0-9-]*" placeholder="loadtest-demo-001" class="mt-2 w-full rounded-xl border border-gray-200 bg-gray-50 px-3 py-2.5 text-sm focus:border-primary focus:ring-primary"></label></div>
        @if($errors->any())<p class="mt-3 text-sm text-red-600">{{ $errors->first() }}</p>@endif
        <button class="mt-5 rounded-lg bg-primary px-5 py-2.5 text-sm font-semibold text-white hover:bg-primary/90">Buat akun & CSV</button>
    </form>
    <section class="rounded-xl border border-gray-200 bg-white shadow-sm"><div class="border-b border-gray-100 px-6 py-4"><h2 class="font-semibold text-gray-900">Batch tersedia</h2></div><div class="divide-y divide-gray-100">@forelse($batches as $batch)<div class="flex flex-col gap-3 px-6 py-4 lg:flex-row lg:items-center lg:justify-between"><code class="text-sm font-semibold text-primary">{{ $batch }}</code><div class="flex flex-wrap gap-2"><a href="{{ route('super-admin.load-test.download', $batch) }}" class="rounded-lg border border-primary px-3 py-2 text-sm font-medium text-primary hover:bg-primary hover:text-white">Unduh CSV</a><form method="POST" action="{{ route('super-admin.load-test.reset', $batch) }}" class="flex gap-2">@csrf<select name="tryout_id" required class="rounded-lg border-gray-300 text-sm"><option value="">Pilih tryout reset</option>@foreach($tryouts as $tryout)<option value="{{ $tryout->tryout_id }}">#{{ $tryout->tryout_id }} {{ $tryout->name }}</option>@endforeach</select><button class="rounded-lg border border-gray-300 px-3 py-2 text-sm text-gray-700 hover:bg-gray-50">Reset percobaan</button></form><form method="POST" action="{{ route('super-admin.load-test.destroy', $batch) }}" onsubmit="return confirm('Hapus akun, hasil, dan CSV batch ini?')">@csrf @method('DELETE')<button class="rounded-lg px-3 py-2 text-sm font-medium text-red-600 hover:bg-red-50">Hapus batch</button></form></div></div>@empty<div class="px-6 py-10 text-center text-sm text-gray-500">Belum ada batch load test.</div>@endforelse</div></section>
</div>
@endsection
