<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ClientProfile extends Model
{
    protected $table = 'client_profile';

    protected $fillable = [
        'nama_bimbel',
        'faq_label',
        'live_session_label',
        'logo',
        'favicon',
        'warna_primary',
        'warna_secondary',
        'enable_certificate_management',
        'header_primary_color',
        'sidebar_primary_color',
        'enable_utbk_types',
        'allow_video_thumbnail',
        'payment_mode',
        'payment_bank_name',
        'payment_account_number',
        'payment_account_holder',
        'payment_bank_note',
        'payment_unique_code_enabled',
        'payment_gateway',
        'payment_gateway_mode',
        'xendit_secret_key',
        'xendit_webhook_token',
        'midtrans_server_key',
        'midtrans_client_key',
        'interactive_qris_api_key',
        'interactive_qris_mid',
        'interactive_qris_use_tip',
        'ipaymu_api_key',
        'ipaymu_va',
        'smtp_host',
        'smtp_port',
        'smtp_encryption',
        'smtp_email',
        'smtp_app_password',
        'smtp_notification_email',
        'contact_whatsapp_number',
        'contact_whatsapp_button_text',
        'concurrent_login_limit',
        'footer_enabled',
        'footer_description',
        'footer_copyright',
        'footer_links',
        'footer_address',
        'footer_phone',
        'footer_email',
        'footer_whatsapp',
        'footer_facebook',
        'footer_instagram',
        'footer_twitter',
        'footer_youtube',
        'ai_question_generator_settings',
        'ai_discussion_feature_enabled',
        'ai_discussion_admin_configurable',
        'ai_discussion_settings',
        'ai_gateway_payment_settings',
        'ai_gateway_telegram_settings',
        'admin_assistant_enabled',
        'class_schedule_menu_enabled',
        'recurring_bill_menu_enabled',
        'tutor_chat_enabled',
        'participant_destination_api_enabled',
    ];

    protected $casts = [
        'enable_certificate_management' => 'boolean',
        'header_primary_color' => 'boolean',
        'sidebar_primary_color' => 'boolean',
        'enable_utbk_types' => 'boolean',
        'allow_video_thumbnail' => 'boolean',
        'payment_unique_code_enabled' => 'boolean',
        'concurrent_login_limit' => 'integer',
        'footer_enabled' => 'boolean',
        'footer_links' => 'array',
        'smtp_app_password' => 'encrypted',
        'xendit_secret_key' => 'encrypted',
        'xendit_webhook_token' => 'encrypted',
        'midtrans_server_key' => 'encrypted',
        'midtrans_client_key' => 'encrypted',
        'interactive_qris_api_key' => 'encrypted',
        'interactive_qris_use_tip' => 'boolean',
        'ipaymu_api_key' => 'encrypted',
        'ai_question_generator_settings' => 'encrypted:array',
        'ai_discussion_feature_enabled' => 'boolean',
        'ai_discussion_admin_configurable' => 'boolean',
        'ai_discussion_settings' => 'encrypted:array',
        'ai_gateway_payment_settings' => 'encrypted:array',
        'ai_gateway_telegram_settings' => 'encrypted:array',
        'admin_assistant_enabled' => 'boolean',
        'class_schedule_menu_enabled' => 'boolean',
        'recurring_bill_menu_enabled' => 'boolean',
        'tutor_chat_enabled' => 'boolean',
        'participant_destination_api_enabled' => 'boolean',
    ];
}
