<aside id="logo-sidebar" x-ignore
    class="fixed top-0 left-0 z-40 w-64 h-screen {{ !empty($isPickerMode) ? 'pt-36' : 'pt-20' }} transition-transform -translate-x-full sm:translate-x-0 {{ $sidebarWrapperClasses }}"
    aria-label="Sidebar">
    <div class="h-full px-3 pb-4 overflow-y-auto {{ $sidebarInnerClasses }}">
        <p class="{{ $sectionLabelClass }} text-sm">Menu</p>
        <ul class="space-y-1 font-medium">
            @if($canShowTutorDashboard)
                <li><a href="{{ route('tutor.dashboard') }}" class="flex items-center py-2 px-4 {{ $isTutorDashboardActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-home-line text-[20px] {{ $isTutorDashboardActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Dashboard</span></a></li>
            @endif
            @if($isTutor && $featureVisibility['question_bank'])
                <li><a href="{{ route('admin.question-bank.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.question-bank.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-folder-3-line text-[20px] {{ request()->routeIs('admin.question-bank.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">{{ $isTutorContentIsolated ? 'Bank Soal Saya & Admin' : 'Bank Soal' }}</span></a></li>
            @endif
            @if($isSchoolAdmin)
                <li><a href="{{ route('admin.school.dashboard') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.school.dashboard') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-home-line text-[20px] {{ request()->routeIs('admin.school.dashboard') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Dashboard Sekolah</span></a></li>
                <li><a href="{{ route('admin.school.students') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.school.students') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-group-line text-[20px] {{ request()->routeIs('admin.school.students') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Data Siswa</span></a></li>
                <li><a href="{{ route('admin.school.leaderboard') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.school.leaderboard') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-trophy-line text-[20px] {{ request()->routeIs('admin.school.leaderboard') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Leaderboard</span></a></li>
                <li><a href="{{ route('admin.school.laporan') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.school.laporan') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-file-chart-line text-[20px] {{ request()->routeIs('admin.school.laporan') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Laporan Tryout</span></a></li>
            @elseif(! $isTutor && $featureVisibility['dashboard'])
                <li><a href="{{ route('admin.dashboard') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.dashboard') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-home-line text-[20px] {{ request()->routeIs('admin.dashboard') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Dashboard</span></a></li>
            @endif
            @if(! $isSchoolAdmin && $canShowMasterMenu)
                <li><details id="menu-master" class="group" {{ $isMasterActive ? 'open' : '' }}><summary class="flex items-center justify-between py-2 px-4 cursor-pointer {{ $isMasterActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group" style="list-style: none;"><span class="flex items-center"><i class="ri-stack-line text-[20px] {{ $isMasterActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Manajemen Master</span></span><i class="ri-arrow-down-s-line text-[18px] transition-transform group-open:rotate-180 {{ $isMasterActive ? $iconActiveClass : $iconInactiveClass }}"></i></summary><ul class="mt-1 ms-2 space-y-1">
                    @if($featureVisibility['package'])<li><a href="{{ route('admin.package.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.package.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Manajemen Paket</span></a></li>@endif
                    @if($canShowClassScheduleMenu)<li><a href="{{ route('admin.class-schedules.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ $isClassScheduleActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Kelas & Jadwal</span></a></li>@endif
                    @if($canShowLegacyClassMenu)<li><a href="{{ route('admin.class.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.class.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Manajemen Kelas</span></a></li>@endif
                    @if($featureVisibility['tryout'])<li><a href="{{ route('admin.tryout.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.tryout.*') || request()->routeIs('admin.question.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>{{ $isTutorContentIsolated ? 'Tryout Saya & Admin' : 'Manajemen Tryout' }}</span></a></li>@endif
                    @if($canShowStudyGroupMenu)<li><a href="{{ route('admin.study-groups.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.study-groups.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Rombel / Grup Belajar</span></a></li>@endif
                    @if($canShowMaterialMenu)<li><a href="{{ route('admin.material.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ $isMaterialManagementActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>{{ $isTutorContentIsolated ? 'Materi Saya & Admin' : 'Manajemen Materi' }}</span></a></li>@endif
                    @if($featureVisibility['tes_koran'])<li><a href="{{ route('admin.tes-koran.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ $isTesKoranActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Tes Koran</span></a></li>@endif
                </ul></details></li>
            @endif
            @if($canShowTutorScheduleMenu)
                <li><a href="{{ route('tutor.schedule.index') }}" class="flex items-center py-2 px-4 {{ $isTutorScheduleActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-calendar-line text-[20px] {{ $isTutorScheduleActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Jadwal Saya</span></a></li>
                <li><a href="{{ route('tutor.leave.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('tutor.leave.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-calendar-close-line text-[20px] {{ request()->routeIs('tutor.leave.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Pengajuan Cuti</span></a></li>
                @if($canShowTutorAttendanceMenu)
                <li><a href="{{ route('tutor.attendance.index') }}" class="flex items-center py-2 px-4 {{ $isTutorAttendanceActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-calendar-check-line text-[20px] {{ $isTutorAttendanceActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Absensi Saya</span></a></li>
                @endif
            @endif
            @if($canShowTutorEarningsMenu)
                <li><a href="{{ route('tutor.earnings.index') }}" class="flex items-center py-2 px-4 {{ $isTutorEarningsActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-money-dollar-circle-line text-[20px] {{ $isTutorEarningsActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Penghasilan</span></a></li>
            @endif
            @if($canShowTutorBookingMenu)
                <li><a href="{{ route('tutor.booking.index') }}" class="flex items-center py-2 px-4 {{ $isTutorBookingActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-calendar-schedule-line text-[20px] {{ $isTutorBookingActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Booking</span></a></li>
            @endif
            @if($canShowTutorDevelopmentMenu)
                <li><a href="{{ route('tutor.development.index') }}" class="flex items-center py-2 px-4 {{ $isTutorDevelopmentActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-line-chart-line text-[20px] {{ $isTutorDevelopmentActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Perkembangan</span></a></li>
            @endif
            @if($canShowTutorChatMenu)
                <li><a href="{{ route('tutor.chat.index') }}" class="flex items-center py-2 px-4 {{ $isTutorChatActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-chat-3-line text-[20px] {{ $isTutorChatActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Chat Siswa</span>@if($tutorChatUnreadCount > 0)<span class="ml-auto rounded-full bg-red-500 px-2 py-0.5 text-[10px] font-bold text-white">{{ $tutorChatUnreadCount > 99 ? '99+' : $tutorChatUnreadCount }}</span>@endif</a></li>
            @endif
            @if(! $isSchoolAdmin && ! $isTutor && $featureVisibility['question_bank'])<li><a href="{{ route('admin.question-bank.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.question-bank.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-folder-3-line text-[20px] {{ request()->routeIs('admin.question-bank.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Bank Soal</span></a></li>@endif
            @if($canShowCategoryMenu)
                <li><details id="menu-category" class="group" {{ $isCategoryActive ? 'open' : '' }}><summary class="flex items-center justify-between py-2 px-4 cursor-pointer {{ $isCategoryActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group" style="list-style: none;"><span class="flex items-center"><i class="ri-folder-settings-line text-[20px] {{ $isCategoryActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Kategori</span></span><i class="ri-arrow-down-s-line text-[18px] transition-transform group-open:rotate-180 {{ $isCategoryActive ? $iconActiveClass : $iconInactiveClass }}"></i></summary><ul class="mt-1 ms-2 space-y-1">
                    @if($canShowMaterialCategoryMenu)<li><a href="{{ route('admin.material.material-category.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.material.material-category.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Kategori Subtest</span></a></li>@endif
                    @if($canShowDestinationCategories)<li><a href="{{ route('admin.participant-destination-categories.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.participant-destination-categories.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Tujuan / Instansi</span></a></li>@endif
                </ul></details></li>
            @endif
            @if($canShowUserMenu)
                <li><details id="menu-user" class="group" {{ $isUserActive ? 'open' : '' }}><summary class="flex items-center justify-between py-2 px-4 cursor-pointer {{ $isUserActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group" style="list-style: none;"><span class="flex items-center"><i class="ri-user-2-line text-[20px] {{ $isUserActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Manajemen User</span></span><i class="ri-arrow-down-s-line text-[18px] transition-transform group-open:rotate-180 {{ $isUserActive ? $iconActiveClass : $iconInactiveClass }}"></i></summary><ul class="mt-1 ms-2 space-y-1">
                    @if($featureVisibility['user'])<li><a href="{{ route('admin.user.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.user.*') && !request()->routeIs('admin.user.login-as-page') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Manajemen User</span></a></li><li><a href="{{ route('admin.user.login-as-page') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.user.login-as-page') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Login As User</span></a></li>@endif
                    @if($featureVisibility['akses'])<li><a href="{{ route('admin.akses.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.akses.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Akses User</span></a></li>@endif
                    @if($canShowTutorLeaveMenu)<li><a href="{{ route('admin.tutor-leave.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.tutor-leave.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Pengajuan Cuti Tutor</span></a></li>@endif
                </ul></details></li>
            @endif
            @if($canShowReportMenu)
                <li><details id="menu-report" class="group" {{ $isReportActive ? 'open' : '' }}><summary class="flex items-center justify-between py-2 px-4 cursor-pointer {{ $isReportActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group" style="list-style: none;"><span class="flex items-center"><i class="ri-file-chart-line text-[20px] {{ $isReportActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Laporan Tryout</span></span><i class="ri-arrow-down-s-line text-[18px] transition-transform group-open:rotate-180 {{ $isReportActive ? $iconActiveClass : $iconInactiveClass }}"></i></summary><ul class="mt-1 ms-2 space-y-1">
                    @if($featureVisibility['leaderboard'])<li><a href="{{ route('admin.leaderboard.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.leaderboard.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Leaderboard</span></a></li>@endif
                    @if($featureVisibility['laporan'])<li><a href="{{ route('admin.laporan.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.laporan.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Laporan Tryout</span></a></li>@endif
                    @if($featureVisibility['essay_review'])<li><a href="{{ route('admin.essay-review.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.essay-review.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Koreksi Essay</span></a></li>@endif
                    @if($featureVisibility['feedback'])<li><a href="{{ route('admin.feedback.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.feedback.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Feedback Tryout</span></a></li>@endif
                </ul></details></li>
            @endif
            @if($canShowFinanceSection)
                <li><details id="menu-finance" class="group" {{ $isFinanceActive ? 'open' : '' }}><summary class="flex items-center justify-between py-2 px-4 cursor-pointer {{ $isFinanceActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group" style="list-style: none;"><span class="flex items-center"><i class="ri-wallet-3-line text-[20px] {{ $isFinanceActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Keuangan</span></span><i class="ri-arrow-down-s-line text-[18px] transition-transform group-open:rotate-180 {{ $isFinanceActive ? $iconActiveClass : $iconInactiveClass }}"></i></summary><ul class="mt-1 ms-2 space-y-1">
                    @if($canShowFinanceMenu)<li><a href="{{ route('admin.finance.income.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.finance.income.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Pemasukan</span></a></li><li><a href="{{ route('admin.finance.expenses.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.finance.expenses.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Pengeluaran</span></a></li>@endif
                    @if($canShowPaymentsMenu)<li><a href="{{ route('admin.pembayaran.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.pembayaran.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Pembayaran</span></a></li>@endif
                    @if($canShowRecurringBillMenu)<li><a href="{{ route('admin.recurring-bills.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.recurring-bills.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Tagihan Rutin</span></a></li>@endif
                    @if($canShowTutorPayrollMenu)<li><a href="{{ route('admin.tutor-payrolls.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.tutor-payrolls.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Penggajian Tutor</span></a></li>@endif
                </ul></details></li>
            @endif
            @if($canShowAffiliateMenu)<li><a href="{{ route('admin.affiliate.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.affiliate.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-share-forward-line text-[20px] {{ request()->routeIs('admin.affiliate.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Affiliate</span></a></li>@endif
            @if($canShowDiscountMenu)<li><a href="{{ route('admin.discounts.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.discounts.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-coupon-3-line text-[20px] {{ request()->routeIs('admin.discounts.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Diskon</span></a></li>@endif
            @if($canShowAdminLanding || $canShowAdminArticles)
                <li><details id="menu-general" class="group" {{ $isGeneralActive ? 'open' : '' }}><summary class="flex items-center justify-between py-2 px-4 cursor-pointer {{ $isGeneralActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group" style="list-style: none;"><span class="flex items-center"><i class="ri-global-line text-[20px] {{ $isGeneralActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">General</span></span><i class="ri-arrow-down-s-line text-[18px] transition-transform group-open:rotate-180 {{ $isGeneralActive ? $iconActiveClass : $iconInactiveClass }}"></i></summary><ul class="mt-1 ms-2 space-y-1">
                    @if($canShowAdminLanding)<li><a href="{{ route('admin.general-pages.landing.edit') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.general-pages.landing.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Landing Page</span></a></li>@endif
                    @if($canShowAdminArticles)<li><a href="{{ route('admin.artikel.index') }}" class="flex items-center py-2 pl-12 pr-4 {{ request()->routeIs('admin.artikel.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><span>Artikel</span></a></li>@endif
                </ul></details></li>
            @endif
            @if($featureVisibility['faq'])<li><a href="{{ route('admin.faq.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.faq.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-question-line text-[20px] {{ request()->routeIs('admin.faq.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">{{ $faqLabel }}</span></a></li>@endif
            @if($canShowActivityMenu)<li><a href="{{ route('admin.activity.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.activity.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-history-line text-[20px] {{ request()->routeIs('admin.activity.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Activity</span></a></li>@endif
            @if($canShowCertificateMenu)<li><a href="{{ route('admin.certificate.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.certificate.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-award-line text-[20px] {{ request()->routeIs('admin.certificate.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Manajemen Sertifikat</span></a></li>@endif
            @if($canShowUpdateNotificationsMenu)<li><a href="{{ route('admin.update-notifications.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.update-notifications.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-notification-3-line text-[20px] {{ request()->routeIs('admin.update-notifications.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Notifikasi Update</span></a></li>@endif
            @if($featureVisibility['settings'])<li><a href="{{ route('admin.settings.index') }}" class="flex items-center py-2 px-4 {{ request()->routeIs('admin.settings.*') ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-settings-3-line text-[20px] {{ request()->routeIs('admin.settings.*') ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Pengaturan</span></a></li>@endif
            @if($canShowTutorProfileMenu)
                <li><a href="{{ route('tutor.profile.edit') }}" class="flex items-center py-2 px-4 {{ $isTutorProfileActive ? $linkActiveClass : $linkInactiveClass }} rounded-lg group"><i class="ri-user-settings-line text-[20px] {{ $isTutorProfileActive ? $iconActiveClass : $iconInactiveClass }}"></i><span class="ms-3">Profil Saya</span></a></li>
            @endif
        </ul>
    </div>
</aside>
